### ISSUE TITLE
Is this Wyclef?

### ISSUE THREAD

**Issue by DrAlta** [mkremins/praxish#1]
Wyclef: A Rational Reconstruction of Versu Social Engine says that Wyclef is avaiable on GitHub but I can't find anything named that.  But it does mention Wycef _uses_ Praxish

**Comment by mkremins** [comment]
Yes, Wyclef was the working title of the project for part of its development! Praxish is the official name for ongoing development. The [AIIDE 2023 Praxish paper](https://mkremins.github.io/publications/Praxish_AIIDE2023.pdf) might be a better reference for working with the system as it currently operates.
